name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Write value to Properties-file
        run: |
          cd src/main/resources
          touch application.properties
          echo spring.data.mongodb.uri=${{ secrets.MONGODB_URI }} >> application.properties
          echo spring.data.mongodb.uri=${{ secrets.MONGODB_URI }} >> application.properties
          echo spring.data.mongodb.database=${{ secrets.MONGODB_DATABASE }} >> application.properties
          echo spring.security.oauth2.client.registration.google.client-id=${{ secrets.CLIENT_ID }} >> application.properties
          echo spring.security.oauth2.client.registration.google.client-secret=${{ secrets.CLIENT_SECRET }} >> application.properties
          echo holidays_api_key=${{ secrets.HOLIDAYS_API_KEY }} >> application.properties

      - name: Verify properties file exist
        run: | 
          cd src/main/resources
          cat application.properties > properties.txt
          cat application.properties

#      - name: Build with Maven
#        run: mvn clean install

      - name: Upload response artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: UpdateHolidaysTest
          path: /home/runner/work/Plan_IT_Engine/Plan_IT_Engine/target/surefire-reports/com.example.planit.mongo.UpdateHolidaysTest.txt

      - name: Upload response artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: PlanITApplicationTests
          path: /home/runner/work/Plan_IT_Engine/Plan_IT_Engine/target/surefire-reports/com.example.planit.system.PlanITApplicationTests.txt

      - name: Upload response artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: properties
          path: /home/runner/work/Plan_IT_Engine/Plan_IT_Engine/src/main/resources/properties.txt